name: Sync OAS to ReadMe
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: KC9Vh7XrlXjYuIDoFlGHKEdXPo2BFK1V:605c8c850572a10acfabd875
           
          # OPTIONAL CONFIG, use if necessary
          oas-file-path: 'openapi/model-service-v1.yml'
          api-version: 'v1.0.0'

